[package]
name = "fmap-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16"}
colored = "2.1.0"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"

